
CALL ..\dot_env.bat
SET path=%path%;%VS_DEVENV_DIR%

SET POST_COMMAND_CONFIG_PATH=%~dp0config.bat

if exist %POST_COMMAND_CONFIG_PATH% (
    del /Q %POST_COMMAND_CONFIG_PATH%
)

ECHO SET DLL_PLATFORM=%DLL_PLATFORM%>>%POST_COMMAND_CONFIG_PATH%
ECHO SET UNITY_PLATFORM=%UNITY_PLATFORM%>>%POST_COMMAND_CONFIG_PATH%
ECHO SET DLL_OUTPUT_DIR=%DLL_OUTPUT_DIR%>>%POST_COMMAND_CONFIG_PATH%

CALL %~dp0\post-command.bat

rem devenv --help